# change: github actions
on:
  push:
    branches:
    - master
  
jobs:
    update_map:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v1
              with:
                python-version: '3.8'
                architecture: 'x64'
                ref: ${{ github.head_ref }}
                token: ${{ secrets.PAT }}
                        
            - name: Checkout branch
              run: git switch "${GITHUB_REF:11}"

            - name: 'Start Python'
              run: |
                  python .github/workflows/update_map.py

            - name: Set git remote URL
              run: git remote set-url origin https://$TOKEN:x-oauth-basic@github.com/$GITHUB_REPOSITORY
              env:
                TOKEN: ${{ secrets.TOKEN }}

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                branch: master
                commit_author_email: ilya.chichkov15@gmail.com
                commit_author_name: Ilya Chichkov
                commit_message: Apply map_updater changes
                push_options: --force
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
