# change: github actions
on:
  push:
    branches:
    - master
  
jobs:
    update_map:
        runs-on: ubuntu-latest
        steps:
            - name: 'Basic information'
              run: |
                  echo "Running! ${HOME}"
                  echo "GITHUB_WORKFLOW - ${GITHUB_WORKFLOW}"
                  echo "GITHUB_ACTIONS - ${GITHUB_WORKSPACE}"
                  echo "GITHUB_REPOSITORY - ${GITHUB_REPOSITORY}"
                  echo "GITHUB_ACTION_PATH - ${GITHUB_ACTION_PATH}"
            - name: 'Test'
              run: |
                  echo "HOME"
                  cd ${HOME}
                  ls
                  echo "GITHUB_WORKSPACE"
                  cd ${GITHUB_WORKSPACE}
                  ls
                  echo "GITHUB_WORKFLOW"
                  cd ${GITHUB_WORKFLOW}
                  ls
                  echo "GITHUB_ACTION_PATH"
                  cd ${GITHUB_ACTION_PATH}
                  ls