# change: github actions
on:
  push:
    branches:
    - master
  
jobs:
    update_map:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v1
              with:
                python-version: '3.8'
                architecture: 'x64'
            - name: 'Basic information'
              run: |
                  echo "Running! ${HOME}"
                  echo "GITHUB_WORKFLOW - ${GITHUB_WORKFLOW}"
                  echo "GITHUB_ACTIONS - ${GITHUB_WORKSPACE}"
                  echo "GITHUB_REPOSITORY - ${GITHUB_REPOSITORY}"
                  echo "GITHUB_ACTION_PATH - ${GITHUB_ACTION_PATH}"
            - name: 'Test'
              run: |
                  echo "HOME"
                  cd ${HOME}
                  ls
                  echo "GITHUB_WORKSPACE"
                  cd ${GITHUB_WORKSPACE}
                  ls
                  echo "GITHUB_ACTION_PATH"
                  cd ${GITHUB_ACTION_PATH}
                  ls
            - name: 'Start Python'
              run: |
                  python .github/workflows/update_map.py