# change: github actions
on:
  push:
    branches:
    - master
  
jobs:
    update_map:
        runs-on: ubuntu-latest
        steps:
            - name: 'Test'
              run:
                  echo "Running! ${HOME}"
                  echo "GITHUB_WORKFLOW - ${GITHUB_WORKFLOW}"
                  echo "GITHUB_ACTIONS - ${GITHUB_WORKSPACE}"
                  echo "GITHUB_REPOSITORY - ${GITHUB_REPOSITORY}"
                  cd ${HOME}
                  ls
                  cd ${GITHUB_WORKSPACE}
                  ls